### ISSUE TITLE
[Feature]: Custom diet tooltip color

### ISSUE THREAD

**Issue by khjxiaogu** [TheIllusiveC4/Diet#104]
### What is the new feature or improvement?

As most diet values are beneficial, I would like to add some harmful values whose effect are all negative. However, all tooltips are green, this cause confuse whether that value is good or bad. Also, making tooltip colors match the diet value colors would make tooltips looks much prettier. Just add a configuration to set tooltip text color or respect text formatting like `&a` in language file would be good enough.

**Comment by TheIllusiveC4** [comment]
I will add an additional field to the groups in `diet-groups.toml` which will determine whether a group is intended to be beneficial or harmful, with differing tooltip colors between them to convey the purpose to the player. However, I do not want to make tooltip colors completely customizable because I think it would just overcomplicate the information being conveyed to the player.
