### ISSUE TITLE
[Bug]: Refined Pipes broken

### ISSUE THREAD

**Issue by in360V2** [TheIllusiveC4/Diet#110]
### What happened?

for some reason whenever this mod is installed you cant place the export bus from the refined pipe mod.

### How do you trigger this bug?

1.having Diet installed
2.
3.
...

### Forge Version

1.18.1

### Mod Version

1.18.1

**Comment by in360V2** [comment]
when do you think this could be fixed?
its one of the last mods i'm waiting on for my modpack for me and my friends

**Comment by AlienXtream** [comment]
i know this one is fixed in later versions but its still a problem in 1.16 (which is still a major ish version right now) so i was wondering how viable a back port of this specific fix would be? no worries if its not. i know asking for back ports is generally in poor taste and so im trying to not come across as disrespectful of the effort and time spent on these mods. only reason i ask in this case is due to the relatively severe nature of the issue (and somewhat esoteric issue it results in possibly affecting other mods in 1.16 too).  :)
