### ISSUE TITLE
[Bug]: Mod Conflict

### ISSUE THREAD

**Issue by starsnstr1pes** [TheIllusiveC4/Diet#114]
### What happened?

The Scroll of Harvests mod has a button that overlaps the diet button and makes it hard to get to the diet menu.
![Bad](https://user-images.githubusercontent.com/45908973/153093731-2f6aaef6-743d-4a5d-99bf-3d7d0a814811.png)
![Bad-1](https://user-images.githubusercontent.com/45908973/153093732-76ae814e-fbc2-473a-9641-177710bcbd4e.png)
 

### How do you trigger this bug?

1.There is no trigger for it just a button overlap.
2.
3.
...

### Forge Version

Forge - 39.0.75

### Mod Version

Diet - 1.18.1-1.2.0.2

### Other Relevant Mod Versions

Scroll of Harvests - 1.18.1-1.2.0

**Comment by TheIllusiveC4** [comment]
You have to change the `buttonX` and `buttonY` values in `diet-client.toml` in your `configs` folder, so that this overlap doesn't occur.

There's no other reasonable solution, as Diet has no way of knowing what's being rendered there and it would be impossible to account for every single mod that places a button in that area.
