### ISSUE TITLE
[Feature]: Better Hunger always-edible feature incompatibility(?)

### ISSUE THREAD

**Issue by Kzeroko** [TheIllusiveC4/Diet#116]
### What is the new feature or improvement?

I don't know if it is intended or not, when you have full saturation bar, further consumption of food will not add to dietary bar.
If possible, can you add a config so I can choose to let players control their diet even though they are fully saturated? Maybe a feature like if they eat after fully saturated, the food dietary add to will only have 50% value, or can be less.

**Comment by TheIllusiveC4** [comment]
Do you mean a full food bar? Yes, this is intentional. Diet's mechanics are tied directly to the increase/decay of the food bar. Allowing players to increase their diet values without any danger of them decaying defeats the whole purpose of the system. It doesn't matter if you make the penalty 50% or 1%, it would still mean they can eat as much as they want in one sitting and fill all their Diet values to 100%.
