### ISSUE TITLE
[Feature]: Food Group Blacklisting/"clearing" or "overriding" values directly

### ISSUE THREAD

**Issue by Darkmega18** [TheIllusiveC4/Diet#128]
### What is the new feature or improvement?

I'd like if there was a way that you could specifically do several options towards foods when configuring your own modpacks:

**Partial Blacklisting/Clearing:** Item id goes in, with optional food group that you don't want the item to be included in (or left blank for defaulting to all) and then item's value in whatever food group is forcibly negated regardless of what another mod says or tags say the item will not provide dietary values. But will remain in tags for other purposes, like item grouping etc.

**Overriding:** Config with item ids followed by the wanted food group names. This forces it to take on the listed food groups with the item. good in the case of unruly or specific food items you want to control the power of directly and without challenge incase their components create weird combinations or you're recategorizing and want to be ultra specific.

both of these would be useful when the basic 4 food groups aren't wanted and you want to design your own combinations but some mods might have their own compatibilities or the combinations might make undesireable food values and such. With a direct override config side to fall back to you can do some hard configuring this way rather than letting the tags work if they're failing you.

**Comment by TheIllusiveC4** [comment]
I'm not sure what this would accomplish that can't also be done with tags. And I'm overall hesitant to add a way to do this through configs because I want to limit the number of sources that food groups can come from. Currently, users only need to worry about tags to check for food groups. With this, they would have to worry about tags and config options.

> Partial Blacklisting/Clearing: Item id goes in, with optional food group that you don't want the item to be included in (or left blank for defaulting to all) and then item's value in whatever food group is forcibly negated regardless of what another mod says or tags say the item will not provide dietary values. But will remain in tags for other purposes, like item grouping etc.

This can be done with the `"remove"` array in a tag file to remove an item from a particular tag.

> Overriding: Config with item ids followed by the wanted food group names. This forces it to take on the listed food groups with the item. good in the case of unruly or specific food items you want to control the power of directly and without challenge incase their components create weird combinations or you're recategorizing and want to be ultra specific.

I'm not sure I understand the benefit of this over just using the tags. The tags can be used to override anything. You can set the `"replace"` value to `true` and all previous entries will be cleared, giving you a blank slate for that tag.

Overall, I'm just not sure what you mean by tags failing you. They will only fail if you've formatted them incorrectly, otherwise they will do exactly as you expect. For example, putting any item into the `diet:grains` tag will directly give them that food group without any concern as to its components or what any mod says about it.

Can you elaborate on why you believe this feature has uses that cannot be provided by tags alone?

**Comment by Darkmega18** [comment]
well, it was an issue until I actually knew what the ingredients tag did. cause it's not in the wiki. so I didn't know I could stop everything from contributing it's own values to everything else and making a nightmare happen.

once I threw everything into ingredients everyone calmed down and stopped getting values they weren't meant to cause a bottle of water was somehow pulling a small about of a food group from somewhere I had no idea from and then proliferating it throughout most of vanilla food pantry. >_>'

so, this is kinda not needed now. you just need to update your wiki so I don't need to chance upon the fix in your changelog while checking what features you added in the past after being frustrated with it for an hour and my friend giving up and calling vanilla food pantry a garbage mod cause he thought VFP was somehow pulling values from thin air when it was just extensively cross tagged with many things and extrapolating dietary values from places it shouldn'tve.

**Comment by TheIllusiveC4** [comment]
Fair enough, I should note that somewhere. I should also make a configuration option for the value generation so that people can turn it off if they just want everything to be tagged and not generated.

I'll leave this issue open until I get all of that done.

**Comment by Darkmega18** [comment]
> Fair enough, I should note that somewhere. I should also make a configuration option for the value generation so that people can turn it off if they just want everything to be tagged and not generated.
> 
> I'll leave this issue open until I get all of that done.

good idea. then I don't need to toss everything into ingredients to stop it if I'm making something kinda specific with more unique-ish tags and rules to it.
