### ISSUE TITLE
[Bug]: When using force Unicode fonts, the nutrient group percentage number is displayed incorrectly in the gui interface

### ISSUE THREAD

**Issue by TheDreamsCreator** [TheIllusiveC4/Diet#147]
### What happened?

When using force Unicode fonts, the nutrient group percentage number is displayed incorrectly in the gui interface.
![image](https://user-images.githubusercontent.com/76772876/237056406-7ecef29c-247a-453d-8244-7daa4bc1289a.png)
![image](https://user-images.githubusercontent.com/76772876/237056453-3419a8e5-e553-41b8-ac7a-63cc3b767884.png)

### How do you trigger this bug?

1.
2.
3.
...

### Forge Version

40.2.0

### Mod Version

1.3.2.0

**Comment by TheDreamsCreator** [comment]
With mandatory unicode fonts turned off, the percentage number border displays normally.
![image](https://user-images.githubusercontent.com/76772876/237061323-c476e4f3-3e4b-4d8a-a2ab-27ad46c343cb.png)

**Comment by TheIllusiveC4** [comment]
This seems to be just vanilla Minecraft behavior, and I'm unsure how I could address it. The numbers are formatted in the same manner as the vanilla experience bar, which also displays this same behavior when forcing Unicode fonts. While not ideal, this seems like the correct behavior and I'm not sure what an alternative would be since I rely on the vanilla method to draw the font. It seems like it would be best to address this with Mojang themselves.

![2023-06-05_22 34 22](https://github.com/TheIllusiveC4/Diet/assets/29991504/48dc5a92-841e-4823-864b-063685b15b25)
