### ISSUE TITLE
[Suggestion] Move config from world folder to config folder

### ISSUE THREAD

**Issue by Yzelast** [TheIllusiveC4/Diet#44]
I'm making a hardcore pack to myself and found out that the effects's config file is stored inside the save folder, so came to ask if the file could be changed to the main config folder like all the other mods. Would be kind annoying have to copy the file to another save every time i die...

**Comment by TheIllusiveC4** [comment]
"Like all the other mods" is a bit misleading, as this is not something inherent only to this mod. There are three types of configs: client, server, and common. Client and common config files are located in the `config` folder in the root Minecraft folder. This is the folder many people are aware of. However, server config files exist on a per-world basis because they must be configurable for different worlds/servers. What you're referring to is just that Diet has server configurations. This system was introduced by Forge and is used by other mods as well.

The solution to your issue is to put your server configuration files in the `defaultconfigs` folder in the root Minecraft folder. This folder houses default server configurations that will be loaded when new worlds are created.
