### ISSUE TITLE
Integrate with Vampirism

### ISSUE THREAD

**Issue by yagoplx** [TheIllusiveC4/Diet#59]
I don't know whether to post this on here or Vampirism Integration's page so I'm just gonna leave it on both.
There is a pack with Diet I want to add Vampirism to, but I would like to have a feature wherein if a player becomes a vampire, they no longer get any benefits from eating food, thus, this mod should basically give no bonuses or visible nutrition stats for them. Things like hiding the button on the inventory, for one.

You can find Vampirism here:
https://github.com/TeamLapen/Vampirism
https://github.com/TeamLapen/VampirismIntegrations
https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire
https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations

**Comment by TheIllusiveC4** [comment]
On a very basic level, this can be accomplished. Ideally, from Vampirism Integration's side. What they would do is call `DietCapability.get(player).setActive(false)` when the player becomes a vampire to disable the diet tracking. This will keep the button and GUI available, but the values will all be grayed out to indicate that none of them are active.

On a bigger picture level, I'm going to leave this issue open for a bit because there's a possibility that Vampirism Integration wants the integration to be different and there might need to be further discussion in this thread.

**Comment by yagoplx** [comment]
Hmm, I have a feeling that vampirism integrations hasn't been active for a while now, so I'm not sure what to do really.

**Comment by maxanier** [comment]
yagoplx, you are in luck I just got he integrations development setup running again after hours of fighting gradle, maven and bad documentation/dependencies from other mods. So I'm ready for new features.

TheIllusiveC4: Sounds, good, I will do that.

**Comment by TheIllusiveC4** [comment]
Let me know if you run into any issues with the integration, the Diet API is still largely untested and this would be the first time to my knowledge that a mod is using this specific feature.

**Comment by yagoplx** [comment]
There is something else minor to note and it is that the vampirism mod's button is put under the diet one. This can be easily fixed by setting 		`overrideGuiSkillButtonX` to offset it on the vampirism client config but since the diet button isn't very useful for a vampire, shouldn't it be hidden as well? I mean, it's no big deal, but...

**Comment by TheIllusiveC4** [comment]
It looks like this was completed on Vampirism Integration's side, so I'll close this issue.
