### ISSUE TITLE
[Suggestion]: New group suggestion

### ISSUE THREAD

**Issue by Night-Govery** [TheIllusiveC4/Diet#98]
### What is the new support or change you're requesting?

I think the default five group is a little simple to reach 100% and some food(like pumpkin pie and bread) do not exist in any group.
The purpose of this mod, in my opinion, is to encourage player plant more(carrot and melon) and feed more(bee and fish), so I desgin a new system which include 10 groups and each vanilla food is used effectively.

Here is my file and  hope this mod will be more popular! :)
[diet.zip](https://github.com/TheIllusiveC4/Diet/files/7606815/diet.zip)

**Comment by TheIllusiveC4** [comment]
The default food groups are based on the traditional five food groups, except I've replaced dairy with sugars because it makes more sense in a Minecraft context. I've purposefully kept it simple because a lot of users and modpacks won't customize these groups at all and I have to consider ease of accessibility. The current five are easy to identify and comprehend.

Although it may not seem like much more, doubling the amount of groups to 10 adds a significant amount to what players are expected to look at and manage. This also means that some modded foods may easily have 8+ food groups attached and that's a lot to take in when you're looking at the tooltips for all the food you have available. I think 5 is both the sweet spot and the upper limit to what I'm willing to add by default.

You may not agree and I understand that there are players who may be looking for a more in-depth and comprehensive diet system, which is why I've made it customizable to the extent where you can add and configure the food groups as advanced as you'd like. However, by default, I have to keep it simple. It's a better user experience if the default is simple and can be made more in-depth than the other way around.

>  some food(like pumpkin pie and bread) do not exist in any group

Not sure what you mean by this, I just tested this myself and, by default, Pumpkin Pie and Bread have food groups. Pumpkin Pie has Sugars, Proteins, and Vegetables while Bread has Grains.

**Comment by Night-Govery** [comment]
Thanks for your replying and give me such a patient answer!
I have get your desgin idea of the default five group from the perspective of a mod developer.

> by default, Pumpkin Pie and Bread have food groups. Pumpkin Pie has Sugars, Proteins, and Vegetables while Bread has Grains.
But I have just check out the mod file(diet-forge-1.16.5-1.0.1.1.jar\data\diet\tags\items\) and bread is not in the grains group(I get "minecraft:wheat" and "minecraft:cake")

**grains.json**
![image](https://user-images.githubusercontent.com/61444002/143567361-b53d1d25-ccf1-4896-b92d-b501d4590c04.png)

And pumpkin pie is the same problem with bread.

**vegetables.json**
![image](https://user-images.githubusercontent.com/61444002/143567467-1e31dae7-fe00-48ed-96bb-8b13ba2c22cd.png)

Maybe you just forget to update the "items" while your local file is correct?

By the way, you are a great developer！

**Comment by TheIllusiveC4** [comment]
Ah, I see what you mean now. Did you check the items in-game?

They are not tagged because Diet uses a system that can generate the correct diet groups for an item automatically. Since Bread is made from `minecraft:wheat` and that is tagged as `grains` already, Diet recognizes that Bread belongs in the `grains` group. Similarly, Pumpkin Pie's ingredients of `minecraft:sugar`, `minecraft:pumpkin`, and `minecraft:egg` give that item its groupings as well. You can see all these ingredients are tagged, despite the fact these ingredients are not edible by themselves. This is because they are used to give diet groupings to the food they create.

**Comment by Night-Govery** [comment]
Oh, I have just check it in-game and the bread display the value correctly!
(I think the old version have this problem and you fix it)
Thank you!
